pmorie/osb-starter-pack

.travis.yml
pkg/broker/logic.go

Add travis config

---

pkg/broker/broker.go
pkg/broker/logic.go

@LiliC I tried to outline the separation of responsibilities between the APISurface and BusinessLogic here, using provision as an example.  What do you think about this?

Clarify relationship of APISurface and BusinessLogic

---

pkg/broker/logic.go

@onyiny-ang, do you think this is useful information to add?

Add information about OSB API operations

---

pkg/broker/broker.go
pkg/broker/constants.go
pkg/broker/logic.go
pkg/broker/util.go

Basically just taking this a little farther and turning some comments into psuedoish code (that coincidentally happens to compile).
cc @LiliC

Rough out pattern for mux handlers

---

.gitignore
Makefile
cmd/servicebroker/main.go
cmd/servicebroker/options.go
pkg/server/server.go

Initial code for server and main pkgs. Also did some changes to the Makefile.

Add main and server pkg

---

pkg/broker/broker.go

This is just to get initial feedback on the handler functions, if I am going in the right direction? :) Thanks!

Make DeprovisionHandler work

---

Makefile
charts/servicebroker/Chart.yaml
charts/servicebroker/templates/broker.yaml
charts/servicebroker/values.yaml
image/Dockerfile

Add a `deploy-helm` directive to the makefile so you can do:
```
$ git clone git://github.com/pmorie/go-open-service-broker-skeleton
$ make deploy-helm
```
...and it works :)

Add deploy-helm Makefile directive

---

README.md
cmd/servicebroker/main.go
pkg/broker/constants.go
pkg/broker/logic.go
pkg/rest/apisurface.go
pkg/rest/util.go
pkg/server/server.go
pkg/user/cli.go
pkg/user/doc.go
pkg/user/logic.go

Kind of big PR (for this little project) that reorganizes the project so that the user should only need to put code into the `pkg/user` package.
@LiliC I will wait for you to take a look at this before merging, since I know you have changes in progress too.

Reorganize so that a single package contains all the user's code

---

.travis.yml
Makefile
README.md
cmd/servicebroker/main.go
pkg/rest/apisurface.go
pkg/server/server.go
pkg/server/server_test.go
pkg/user/doc.go
pkg/user/logic.go

@LiliC wins the project naming award for January 2018, and a chance to compete in the 2018 finals

Rename to osb-starter-pack

---

pkg/broker/logic.go
pkg/rest/apisurface.go
pkg/server/server.go
pkg/server/server_test.go
pkg/user/logic.go

This PR adds ability to update the service instance. Let me know in case I missed something?
Closes #19.

Add ability to update the service instance

---

README.md

Further tweak README

---

.gitignore
Makefile
README.md

I thought this might be really annoying if you weren't using linux as your host OS.
Depends on #38

Linux binary

---

openshift/starter-pack.yaml

HACK: pull policy

---

pkg/rest/apisurface.go

So this just adds the functionality to the `LastOperationHandler`. As agreed I will tackle the logic part in the `user` pkg next.

Implement LastOperation in APISurface

---

pkg/rest/apisurface.go
pkg/rest/util.go
pkg/server/server_test.go

Made version validation compliant with the spec; had to do a little bit of fussing with the client. I'm not positive all the changes are needed, will test out later and cut a client PR.

Add version validation tests

---

pkg/server/bind_test.go
pkg/server/deprovision_test.go
pkg/server/last_operation_test.go
pkg/server/unbind_test.go
pkg/server/update_instance_test.go

...before refactoring this repo to consuming the OSB stuff from a library

Finish tests

---

Gopkg.lock
Gopkg.toml
pkg/server/bind_test.go
pkg/server/catalog_test.go
pkg/server/deprovision_test.go
pkg/server/last_operation_test.go
pkg/server/provision_test.go
pkg/server/server_test.go
pkg/server/update_instance_test.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/client.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/interface.go

Bump client and make tests easier to debug

---

pkg/broker/logic.go
pkg/rest/apisurface.go
pkg/server/bind_test.go
pkg/server/catalog_test.go
pkg/server/deprovision_test.go
pkg/server/last_operation_test.go
pkg/server/provision_test.go
pkg/server/server_test.go
pkg/server/unbind_test.go
pkg/server/update_instance_test.go
pkg/user/logic.go

See https://github.com/pmorie/osb-starter-pack/issues/57

 WIP: Add RequestContext object to BusinessLogic operations

---

charts/servicebroker/templates/NOTES.txt
charts/servicebroker/templates/broker.yaml

Currently the name and namespace was hardcoded so if the user did not change it, things would not work correctly.
As for the `NOTES.txt` file think it could serve as a great way to add docs there, what the next steps could be. As this file is displayed when the chart is installed. If you have any suggestions what to add there?

Helm fixes

---

Gopkg.lock
Gopkg.toml
vendor/github.com/pmorie/osb-broker-lib/pkg/rest/apisurface.go

To add originating identity support

Bump dep on osb-broker-lib to 0.0.2

---

Gopkg.lock
Gopkg.toml
pkg/broker/logic.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/constants.go
vendor/github.com/pmorie/go-open-service-broker-client/v2/types.go
vendor/github.com/pmorie/osb-broker-lib/pkg/broker/interface.go
vendor/github.com/pmorie/osb-broker-lib/pkg/metrics/metrics.go
vendor/github.com/pmorie/osb-broker-lib/pkg/rest/apisurface.go
vendor/github.com/pmorie/osb-broker-lib/pkg/server/server.go

Closes https://github.com/pmorie/osb-starter-pack/issues/74

Bump osb-broker-lib to 0.0.4

---

.gitignore
pkg/broker/logic.go

This should fix the provision issue with same id and non-matching class/plan.
Update will need some thought too

Record the service class and plan for provision.

---

Makefile
openshift/deploy.sh
openshift/starter-pack.yaml

I missed some key integration on enabling Broker with SSL.  
Thanks @shawn-hurley

fix openshift ssl integration
